
/* autoimport:start */
import { UI512ElementWithText, UI512ElementWithHighlight, UI512BtnStyle, UI512ElementButtonGeneral, UI512ElButton, UI512ElLabel, UI512FldStyle, UI512ElTextField, UI512ElCanvasPiece, GridLayout, UI512ElGroup, UI512Application, ElementObserverToTwo } from "../ui512/ui512elements.js";
import { ChangeContext, ElementObserverVal, ElementObserver, ElementObserverNoOp, ElementObserverDefault, elementObserverNoOp, elementObserverDefault, UI512Gettable, UI512Settable, UI512Element } from "../ui512/ui512elementsbase.js";
import { specialCharOnePixelSpace, specialCharFontChange, specialCharZeroPixelChar, specialCharCmdSymbol, specialCharNumNewline, specialCharNumZeroPixelChar, largearea, RenderTextArgs, FormattedText, TextFontStyling, textFontStylingToString, stringToTextFontStyling, TextFontSpec, TextRendererGrid, TextRendererFont, TextRendererFontCache, CharRectType, TextRendererFontManager, renderTextArgsFromEl, Lines } from "../ui512/ui512rendertext.js";
import { RectOverlapType, RectUtils, ModifierKeys, osTranslateModifiers, toShortcutString, DrawableImage, CanvasWrapper, UI512Cursors, UI512CursorAccess, getColorFromCanvasData, MenuConsts, ScrollConsts, ScreenConsts, getStandardWindowBounds, sleep, compareCanvas, CanvasTestParams, testUtilCompareCanvasWithExpected } from "../ui512/ui512renderutils.js";
import { makeUI512ErrorGeneric, checkThrowUI512, makeUI512Error, ui512RespondError, assertTrue, assertEq, assertTrueWarn, assertEqWarn, throwIfUndefined, ui512ErrorHandling, O, refparam, Util512, findStrToEnum, getStrToEnum, findEnumToStr, getEnumToStrOrUnknown, scontains, slength, setarr, cast, isString, fitIntoInclusive, RenderComplete, defaultSort, LockableArr, RepeatingTimer, IFontManager, IIconManager, IUI512Session, Root, OrderedHash, BrowserOSInfo, Tests_BaseClass, CharClass, GetCharClass, MapKeyToObject, MapKeyToObjectCanSet } from "../ui512/ui512utils.js";
import { UI512Lang, UI512LangNull } from  "../locale/lang-base.js";
/* autoimport:end */

// draws borders like buttons with shadows, window headers, and rounded rectangles

export class UI512ViewDrawBorders {
    didFallbackToSimpleRect = false;
    constructor(
        public canvas: CanvasWrapper,
        public bx: number,
        public by: number,
        public w: number,
        public h: number,
        public root: Root,
        public complete: RenderComplete
    ) {}

    public dr(x: number, y: number, w: number, h: number, color: string) {
        let fillcolor = "";
        if (color === "w" || color === "white") {
            fillcolor = "white";
        } else if (color === "b" || color === "black") {
            fillcolor = "black";
        } else if (color === "t") {
            return; // transparent, don't draw anything
        } else {
            assertTrue(false, "3E|unknown color " + color);
        }

        this.canvas.fillRect(x, y, w, h, this.bx, this.by, this.w, this.h, fillcolor, true);
    }

    public fallbackToSimpleRect(highlight: boolean) {
        if (highlight) {
            this.drawboxthinborderclicked();
        } else {
            this.drawboxthinborder();
        }

        this.didFallbackToSimpleRect = true;
    }

    // BEGIN:GENERATED CODE --------------------------------------------------------------------------------------------------------
    // CODE GENERATED BY get-ui-borders.py, any changes here will be lost ----------------------------------------------------------
    // osboxmodal.png
    public drawosboxmodal() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (6 + 6) + 1;
        if (w < 13) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 12) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 12) {
            return this.fallbackToSimpleRect(false);
        }

        // drawing left side
        stre_y = h - (106 - 95);
        y = by;
        this.dr(bx + 0, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 0, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 0, y, 1, 6, "b");
        y += 6;

        y = by;
        this.dr(bx + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 1, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 1, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 1, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 1, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 2, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 2, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 2, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 3, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 3, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 3, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 3, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 3, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 4, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 4, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 4, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 4, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 4, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + 5, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 5, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 5, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 5, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 5, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 5, y, 1, 1, "b");
        y += 1;

        // drawing middle
        y = by;
        this.dr(bx + 6, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 6, y, stre_x, 2, "w");
        y += 2;
        this.dr(bx + 6, y, stre_x, 2, "b");
        y += 2;
        this.dr(bx + 5, by + 5, stre_x, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 6, y, stre_x, 1, "w");
        y += 1;
        this.dr(bx + 6, y, stre_x, 2, "b");
        y += 2;
        this.dr(bx + 6, y, stre_x, 2, "w");
        y += 2;
        this.dr(bx + 6, y, stre_x, 1, "b");
        y += 1;

        // drawing right side
        stre_y = h - (106 - 95);
        y = by;
        this.dr(bx + w - 6 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 6 + 0, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 6 + 0, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 6 + 0, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + w - 6 + 0, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 6 + 0, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 6 + 0, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 6 + 0, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + w - 6 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 6 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 6 + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 6 + 1, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + w - 6 + 1, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 6 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 6 + 1, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + w - 6 + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 6 + 2, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 6 + 2, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 6 + 2, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + w - 6 + 2, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 6 + 2, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 6 + 2, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + w - 6 + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 6 + 3, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 6 + 3, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + w - 6 + 3, y, 1, 5, "w");
        y += 5;
        this.dr(bx + w - 6 + 3, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + w - 6 + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 6 + 4, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 6 + 4, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + w - 6 + 4, y, 1, 5, "w");
        y += 5;
        this.dr(bx + w - 6 + 4, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + w - 6 + 5, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 6 + 5, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + w - 6 + 5, y, 1, 6, "b");
        y += 6;

        return true;
    }
    // osboxshadow.png
    public drawosboxshadow() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (2 + 3) + 1;
        if (w < 6) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 5) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 5) {
            return this.fallbackToSimpleRect(false);
        }

        // drawing left side
        stre_y = h - (44 - 40);
        y = by;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 0, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + 0, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr(bx + 0, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 1, by + 1, 1, stre_y, "w");
        y = by + 1 + stre_y;
        this.dr(bx + 1, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;

        // drawing middle
        y = by;
        this.dr(bx + 2, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 1, by + 1, stre_x, stre_y, "w");
        y = by + 1 + stre_y;
        this.dr(bx + 2, y, stre_x, 1, "w");
        y += 1;
        this.dr(bx + 2, y, stre_x, 2, "b");
        y += 2;

        // drawing right side
        stre_y = h - (44 - 40);
        y = by;
        this.dr(bx + w - 3 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 3 + 0, by + 1, 1, stre_y, "w");
        y = by + 1 + stre_y;
        this.dr(bx + w - 3 + 0, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 3 + 0, y, 1, 2, "b");
        y += 2;

        y = by;
        this.dr(bx + w - 3 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 3 + 1, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + w - 3 + 1, y, 1, 3, "b");
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 3) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 3 + 2, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + w - 3 + 2, y, 1, 3, "b");
        y += 3;

        return true;
    }
    // osboxshadowclicked.png
    public drawosboxshadowclicked() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (2 + 3) + 1;
        if (w < 6) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 4) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 4) {
            return this.fallbackToSimpleRect(true);
        }

        // drawing left side
        stre_y = h - (44 - 41);
        y = by;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 0, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 0, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 1, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;

        // drawing middle
        y = by;
        this.dr(bx + 2, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 1, by + 1, stre_x, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + 2, y, stre_x, 2, "b");
        y += 2;

        // drawing right side
        stre_y = h - (44 - 41);
        y = by;
        this.dr(bx + w - 3 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 3 + 0, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + w - 3 + 0, y, 1, 2, "b");
        y += 2;

        y = by;
        this.dr(bx + w - 3 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 3 + 1, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + w - 3 + 1, y, 1, 2, "b");
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 3) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 3 + 2, by + 1, 1, stre_y, "b");
        y = by + 1 + stre_y;
        this.dr(bx + w - 3 + 2, y, 1, 2, "b");
        y += 2;

        return true;
    }
    // osbtn.png
    public drawosbtn() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (5 + 5) + 1;
        if (w < 11) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 8) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 8) {
            return this.fallbackToSimpleRect(false);
        }

        // drawing left side
        stre_y = h - (21 - 14);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 0, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 0, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 1, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + 1, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr(bx + 1, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 2, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 2, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + 2, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 3, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 3, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 4, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 4, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + 4, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;

        // drawing middle
        y = by;
        this.dr(bx + 5, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 5, y, stre_x, 2, "w");
        y += 2;
        this.dr(bx + 4, by + 3, stre_x, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + 5, y, stre_x, 3, "w");
        y += 3;
        this.dr(bx + 5, y, stre_x, 1, "b");
        y += 1;

        // drawing right side
        stre_y = h - (21 - 14);
        y = by;
        this.dr(bx + w - 5 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 5 + 0, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 5 + 0, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 0, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 5 + 0, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + w - 5 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 5 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 5 + 1, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 1, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 5 + 1, y, 1, 1, "b");
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 5 + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 5 + 2, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 5 + 2, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 2, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 5 + 2, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 5 + 3, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 5 + 3, by + 3, 1, stre_y, "w");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 3, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 5 + 3, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 5 + 4, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 4, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, "t") */
        y += 3;

        return true;
    }
    // osbtnclicked.png
    public drawosbtnclicked() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (5 + 5) + 1;
        if (w < 11) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 8) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 8) {
            return this.fallbackToSimpleRect(true);
        }

        // drawing left side
        stre_y = h - (21 - 14);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 0, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 0, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 1, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + 1, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 1, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 2, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 2, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + 2, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 3, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 3, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + 3, y, 1, 4, "b");
        y += 4;

        y = by;
        this.dr(bx + 4, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 4, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + 4, y, 1, 4, "b");
        y += 4;

        // drawing middle
        y = by;
        this.dr(bx + 5, y, stre_x, 3, "b");
        y += 3;
        this.dr(bx + 4, by + 3, stre_x, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + 5, y, stre_x, 4, "b");
        y += 4;

        // drawing right side
        stre_y = h - (21 - 14);
        y = by;
        this.dr(bx + w - 5 + 0, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 5 + 0, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 0, y, 1, 4, "b");
        y += 4;

        y = by;
        this.dr(bx + w - 5 + 1, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 5 + 1, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 1, y, 1, 4, "b");
        y += 4;

        y = by;
        /* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 5 + 2, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 5 + 2, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 2, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 5 + 3, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 5 + 3, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 3, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 5 + 4, by + 3, 1, stre_y, "b");
        y = by + 3 + stre_y;
        this.dr(bx + w - 5 + 4, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, "t") */
        y += 3;

        return true;
    }
    // osdefaultbtn.png
    public drawosdefaultbtn() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (8 + 8) + 1;
        if (w < 17) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 16) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 16) {
            return this.fallbackToSimpleRect(false);
        }

        // drawing left side
        stre_y = h - (29 - 14);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 5, "t") */
        y += 5;
        this.dr(bx + 0, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 0, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 0, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 0, y, 1, 5, "t") */
        y += 5;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 1, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 1, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 1, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr(bx + 1, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + 2, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 2, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 2, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr(bx + 2, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr(bx + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 3, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 3, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 3, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + 3, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 3, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr(bx + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 4, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 4, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 4, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 4, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 4, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 5, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 5, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 5, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + 5, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 5, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 5, y, 1, 4, "b");
        y += 4;

        y = by;
        this.dr(bx + 6, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 6, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 6, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 6, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 6, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + 6, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 6, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 6, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 6, y, 1, 3, "b");
        y += 3;

        y = by;
        this.dr(bx + 7, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 7, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 7, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 7, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 7, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + 7, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 7, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 7, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 7, y, 1, 3, "b");
        y += 3;

        // drawing middle
        y = by;
        this.dr(bx + 8, y, stre_x, 3, "b");
        y += 3;
        this.dr(bx + 8, y, stre_x, 1, "w");
        y += 1;
        this.dr(bx + 8, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 8, y, stre_x, 2, "w");
        y += 2;
        this.dr(bx + 7, by + 7, stre_x, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + 8, y, stre_x, 3, "w");
        y += 3;
        this.dr(bx + 8, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 8, y, stre_x, 1, "w");
        y += 1;
        this.dr(bx + 8, y, stre_x, 3, "b");
        y += 3;

        // drawing right side
        stre_y = h - (29 - 14);
        y = by;
        this.dr(bx + w - 8 + 0, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 0, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 8 + 0, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 0, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 0, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 8 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 8 + 0, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 0, y, 1, 3, "b");
        y += 3;

        y = by;
        this.dr(bx + w - 8 + 1, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 8 + 1, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 1, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 8 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 1, y, 1, 3, "b");
        y += 3;

        y = by;
        this.dr(bx + w - 8 + 2, y, 1, 4, "b");
        y += 4;
        this.dr(bx + w - 8 + 2, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 2, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 8 + 2, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 2, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 2, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 8 + 2, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 2, y, 1, 4, "b");
        y += 4;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 8 + 3, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 8 + 3, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 8 + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 8 + 3, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 8 + 4, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 8 + 4, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 4, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 4, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 4, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + w - 8 + 5, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 8 + 5, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 5, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 8 + 6, y, 1, 4, "b");
        y += 4;
        this.dr(bx + w - 8 + 6, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 6, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, "t") */
        y += 5;
        this.dr(bx + w - 8 + 7, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 8 + 7, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 7, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, "t") */
        y += 5;

        return true;
    }
    // osdefaultbtnclicked.png
    public drawosdefaultbtnclicked() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (8 + 8) + 1;
        if (w < 17) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 16) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 16) {
            return this.fallbackToSimpleRect(true);
        }

        // drawing left side
        stre_y = h - (29 - 14);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 5, "t") */
        y += 5;
        this.dr(bx + 0, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 0, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 0, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 0, y, 1, 5, "t") */
        y += 5;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 1, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 1, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 1, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr(bx + 1, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + 2, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 2, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 2, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr(bx + 2, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr(bx + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 3, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 3, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 3, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + 3, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 3, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr(bx + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 4, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 4, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 4, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 4, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 4, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 5, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 5, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 5, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 5, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 5, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 5, y, 1, 4, "b");
        y += 4;

        y = by;
        this.dr(bx + 6, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 6, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 6, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 6, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 6, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 6, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 6, y, 1, 3, "b");
        y += 3;

        y = by;
        this.dr(bx + 7, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 7, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 7, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 7, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 7, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 7, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 7, y, 1, 3, "b");
        y += 3;

        // drawing middle
        y = by;
        this.dr(bx + 8, y, stre_x, 3, "b");
        y += 3;
        this.dr(bx + 8, y, stre_x, 1, "w");
        y += 1;
        this.dr(bx + 8, y, stre_x, 3, "b");
        y += 3;
        this.dr(bx + 7, by + 7, stre_x, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + 8, y, stre_x, 4, "b");
        y += 4;
        this.dr(bx + 8, y, stre_x, 1, "w");
        y += 1;
        this.dr(bx + 8, y, stre_x, 3, "b");
        y += 3;

        // drawing right side
        stre_y = h - (29 - 14);
        y = by;
        this.dr(bx + w - 8 + 0, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 0, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 0, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 0, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 0, y, 1, 4, "b");
        y += 4;
        this.dr(bx + w - 8 + 0, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 0, y, 1, 3, "b");
        y += 3;

        y = by;
        this.dr(bx + w - 8 + 1, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 8 + 1, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 1, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 1, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 1, y, 1, 3, "b");
        y += 3;

        y = by;
        this.dr(bx + w - 8 + 2, y, 1, 4, "b");
        y += 4;
        this.dr(bx + w - 8 + 2, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 2, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 8 + 2, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 2, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 2, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 2, y, 1, 4, "b");
        y += 4;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 8 + 3, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 8 + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 8 + 3, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 8 + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 8 + 3, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 8 + 4, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 8 + 4, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 8 + 4, by + 7, 1, stre_y, "w");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 4, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 8 + 4, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + w - 8 + 5, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 8 + 5, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 5, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 8 + 6, y, 1, 4, "b");
        y += 4;
        this.dr(bx + w - 8 + 6, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 6, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, "t") */
        y += 5;
        this.dr(bx + w - 8 + 7, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 8 + 7, by + 7, 1, stre_y, "b");
        y = by + 7 + stre_y;
        this.dr(bx + w - 8 + 7, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, "t") */
        y += 5;

        return true;
    }
    // vpcbtn.png
    public drawvpcbtn() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (9 + 7) + 1;
        if (w < 17) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 13) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 14) {
            return this.fallbackToSimpleRect(false);
        }

        // drawing left side
        stre_y = h - (41 - 29);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 5, "t") */
        y += 5;
        this.dr(bx + 0, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 0, y, 1, 6, "t") */
        y += 6;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 1, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 1, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr(bx + 1, y, 1, 4, "t") */
        y += 4;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 2, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 2, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 2, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 2, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 3, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 3, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 3, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 4, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 4, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 4, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 4, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 5, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 5, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 5, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 5, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 5, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 5, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 6, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 6, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 6, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 6, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 6, y, 1, 2, "b");
        y += 2;

        y = by;
        this.dr(bx + 7, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 7, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 7, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 7, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 7, y, 1, 2, "b");
        y += 2;

        y = by;
        this.dr(bx + 8, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 8, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 8, by + 5, 1, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 8, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 8, y, 1, 2, "b");
        y += 2;

        // drawing middle
        y = by;
        this.dr(bx + 9, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 9, y, stre_x, 4, "w");
        y += 4;
        this.dr(bx + 8, by + 5, stre_x, stre_y, "w");
        y = by + 5 + stre_y;
        this.dr(bx + 9, y, stre_x, 5, "w");
        y += 5;
        this.dr(bx + 9, y, stre_x, 2, "b");
        y += 2;

        // drawing right side
        stre_y = h - (41 - 28);
        y = by;
        this.dr(bx + w - 7 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 0, y, 1, 5, "w");
        y += 5;
        this.dr(bx + w - 7 + 0, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 0, y, 1, 5, "w");
        y += 5;
        this.dr(bx + w - 7 + 0, y, 1, 2, "b");
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 1, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 7 + 1, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 1, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 7 + 1, y, 1, 3, "b");
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 2, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 7 + 2, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 2, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 7 + 2, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + w - 7 + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 7 + 3, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 7 + 3, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 7 + 4, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 7 + 4, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 7 + 4, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 4, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 7 + 4, y, 1, 4, "b");
        y += 4;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, "t") */
        y += 4;
        this.dr(bx + w - 7 + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 7 + 5, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 5, y, 1, 4, "b");
        y += 4;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, "t") */
        y += 6;
        this.dr(bx + w - 7 + 6, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 6, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 5, "t") */
        y += 5;

        return true;
    }
    // vpcbtnclicked.png
    public drawvpcbtnclicked() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (9 + 7) + 1;
        if (w < 17) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 13) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 13) {
            return this.fallbackToSimpleRect(true);
        }

        // drawing left side
        stre_y = h - (41 - 29);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 5, "t") */
        y += 5;
        this.dr(bx + 0, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 0, y, 1, 6, "t") */
        y += 6;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 1, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 1, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 1, y, 1, 4, "t") */
        y += 4;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + 2, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 2, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 2, y, 1, 4, "b");
        y += 4;
        /* (transparent) this.dr(bx + 2, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 3, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 3, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 3, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 3, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr(bx + 3, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 4, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 4, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 4, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 5, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 5, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 5, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr(bx + 5, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 6, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 6, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 6, y, 1, 7, "b");
        y += 7;

        y = by;
        this.dr(bx + 7, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 7, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 7, y, 1, 7, "b");
        y += 7;

        y = by;
        this.dr(bx + 8, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 8, by + 5, 1, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 8, y, 1, 7, "b");
        y += 7;

        // drawing middle
        y = by;
        this.dr(bx + 9, y, stre_x, 5, "b");
        y += 5;
        this.dr(bx + 8, by + 5, stre_x, stre_y, "b");
        y = by + 5 + stre_y;
        this.dr(bx + 9, y, stre_x, 7, "b");
        y += 7;

        // drawing right side
        stre_y = h - (41 - 29);
        y = by;
        this.dr(bx + w - 7 + 0, y, 1, 6, "b");
        y += 6;
        this.dr(bx + w - 7 + 0, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 0, y, 1, 6, "b");
        y += 6;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 1, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 7 + 1, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 1, y, 1, 6, "b");
        y += 6;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 2, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 7 + 2, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 2, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + w - 7 + 3, y, 1, 4, "b");
        y += 4;
        this.dr(bx + w - 7 + 3, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 3, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 7 + 4, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 7 + 4, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 4, y, 1, 4, "b");
        y += 4;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, "t") */
        y += 4;
        this.dr(bx + w - 7 + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 7 + 5, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 5, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, "t") */
        y += 6;
        this.dr(bx + w - 7 + 6, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 6, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 5, "t") */
        y += 5;

        return true;
    }
    // vpcroundrect.png
    public drawvpcroundrect() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (9 + 7) + 1;
        if (w < 17) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 14) {
            return this.fallbackToSimpleRect(false);
        }
        if (h < 14) {
            return this.fallbackToSimpleRect(false);
        }

        // drawing left side
        stre_y = h - (40 - 27);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 6, "t") */
        y += 6;
        this.dr(bx + 0, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 0, y, 1, 6, "t") */
        y += 6;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 4, "t") */
        y += 4;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 1, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 1, y, 1, 1, "w");
        y += 1;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr(bx + 1, y, 1, 4, "t") */
        y += 4;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 2, y, 1, 2, "w");
        y += 2;
        this.dr(bx + 2, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 2, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 2, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 2, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 3, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + 3, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 3, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 3, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 3, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 4, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 4, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 4, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 4, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr(bx + 5, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 5, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 5, y, 1, 4, "w");
        y += 4;
        this.dr(bx + 5, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 5, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 5, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 5, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 6, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 6, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 6, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 6, y, 1, 6, "w");
        y += 6;
        this.dr(bx + 6, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + 7, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 7, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 7, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 7, y, 1, 6, "w");
        y += 6;
        this.dr(bx + 7, y, 1, 1, "b");
        y += 1;

        y = by;
        this.dr(bx + 8, y, 1, 1, "b");
        y += 1;
        this.dr(bx + 8, y, 1, 5, "w");
        y += 5;
        this.dr(bx + 8, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 8, y, 1, 6, "w");
        y += 6;
        this.dr(bx + 8, y, 1, 1, "b");
        y += 1;

        // drawing middle
        y = by;
        this.dr(bx + 9, y, stre_x, 1, "b");
        y += 1;
        this.dr(bx + 9, y, stre_x, 5, "w");
        y += 5;
        this.dr(bx + 8, by + 6, stre_x, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + 9, y, stre_x, 6, "w");
        y += 6;
        this.dr(bx + 9, y, stre_x, 1, "b");
        y += 1;

        // drawing right side
        stre_y = h - (40 - 27);
        y = by;
        this.dr(bx + w - 7 + 0, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 0, y, 1, 5, "w");
        y += 5;
        this.dr(bx + w - 7 + 0, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 0, y, 1, 6, "w");
        y += 6;
        this.dr(bx + w - 7 + 0, y, 1, 1, "b");
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 1, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 1, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 7 + 1, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 1, y, 1, 5, "w");
        y += 5;
        this.dr(bx + w - 7 + 1, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 2, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 2, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 7 + 2, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 2, y, 1, 5, "w");
        y += 5;
        this.dr(bx + w - 7 + 2, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + w - 7 + 3, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 3, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 7 + 3, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 3, y, 1, 4, "w");
        y += 4;
        this.dr(bx + w - 7 + 3, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 7 + 4, y, 1, 1, "b");
        y += 1;
        this.dr(bx + w - 7 + 4, y, 1, 2, "w");
        y += 2;
        this.dr(bx + w - 7 + 4, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 4, y, 1, 3, "w");
        y += 3;
        this.dr(bx + w - 7 + 4, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, "t") */
        y += 4;
        this.dr(bx + w - 7 + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 7 + 5, by + 6, 1, stre_y, "w");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 5, y, 1, 1, "w");
        y += 1;
        this.dr(bx + w - 7 + 5, y, 1, 2, "b");
        y += 2;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, "t") */
        y += 4;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, "t") */
        y += 6;
        this.dr(bx + w - 7 + 6, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 6, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, "t") */
        y += 6;

        return true;
    }
    // vpcroundrectclicked.png
    public drawvpcroundrectclicked() {
        const w = this.w;
        const h = this.h;
        const bx = this.bx;
        const by = this.by;
        let y = 0;
        let stre_y = 0;
        const stre_x = w - (9 + 7) + 1;
        if (w < 17) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 14) {
            return this.fallbackToSimpleRect(true);
        }
        if (h < 14) {
            return this.fallbackToSimpleRect(true);
        }

        // drawing left side
        stre_y = h - (40 - 27);
        y = by;
        /* (transparent) this.dr(bx + 0, y, 1, 6, "t") */
        y += 6;
        this.dr(bx + 0, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 0, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr(bx + 0, y, 1, 6, "t") */
        y += 6;

        y = by;
        /* (transparent) this.dr(bx + 1, y, 1, 4, "t") */
        y += 4;
        this.dr(bx + 1, y, 1, 2, "b");
        y += 2;
        this.dr(bx + 1, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 1, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr(bx + 1, y, 1, 4, "t") */
        y += 4;

        y = by;
        /* (transparent) this.dr(bx + 2, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + 2, y, 1, 3, "b");
        y += 3;
        this.dr(bx + 2, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 2, y, 1, 4, "b");
        y += 4;
        /* (transparent) this.dr(bx + 2, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr(bx + 3, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + 3, y, 1, 4, "b");
        y += 4;
        this.dr(bx + 3, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 3, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr(bx + 3, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 4, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 4, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 4, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr(bx + 4, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr(bx + 5, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + 5, y, 1, 5, "b");
        y += 5;
        this.dr(bx + 5, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 5, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr(bx + 5, y, 1, 1, "t") */
        y += 1;

        y = by;
        this.dr(bx + 6, y, 1, 6, "b");
        y += 6;
        this.dr(bx + 6, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 6, y, 1, 7, "b");
        y += 7;

        y = by;
        this.dr(bx + 7, y, 1, 6, "b");
        y += 6;
        this.dr(bx + 7, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 7, y, 1, 7, "b");
        y += 7;

        y = by;
        this.dr(bx + 8, y, 1, 6, "b");
        y += 6;
        this.dr(bx + 8, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 8, y, 1, 7, "b");
        y += 7;

        // drawing middle
        y = by;
        this.dr(bx + 9, y, stre_x, 6, "b");
        y += 6;
        this.dr(bx + 8, by + 6, stre_x, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + 9, y, stre_x, 7, "b");
        y += 7;

        // drawing right side
        stre_y = h - (40 - 27);
        y = by;
        this.dr(bx + w - 7 + 0, y, 1, 6, "b");
        y += 6;
        this.dr(bx + w - 7 + 0, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 0, y, 1, 7, "b");
        y += 7;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 1, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 7 + 1, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 1, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;
        this.dr(bx + w - 7 + 2, y, 1, 5, "b");
        y += 5;
        this.dr(bx + w - 7 + 2, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 2, y, 1, 6, "b");
        y += 6;
        /* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, "t") */
        y += 1;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, "t") */
        y += 2;
        this.dr(bx + w - 7 + 3, y, 1, 4, "b");
        y += 4;
        this.dr(bx + w - 7 + 3, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 3, y, 1, 5, "b");
        y += 5;
        /* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, "t") */
        y += 2;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, "t") */
        y += 3;
        this.dr(bx + w - 7 + 4, y, 1, 3, "b");
        y += 3;
        this.dr(bx + w - 7 + 4, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 4, y, 1, 4, "b");
        y += 4;
        /* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, "t") */
        y += 3;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, "t") */
        y += 4;
        this.dr(bx + w - 7 + 5, y, 1, 2, "b");
        y += 2;
        this.dr(bx + w - 7 + 5, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 5, y, 1, 3, "b");
        y += 3;
        /* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, "t") */
        y += 4;

        y = by;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, "t") */
        y += 6;
        this.dr(bx + w - 7 + 6, by + 6, 1, stre_y, "b");
        y = by + 6 + stre_y;
        this.dr(bx + w - 7 + 6, y, 1, 1, "b");
        y += 1;
        /* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, "t") */
        y += 6;

        return true;
    }

    // END:GENERATED CODE

    drawboxthinborder() {
        if (this.w > 0 && this.h > 0) {
            let realbordersize = 1;
            // clear it
            this.dr(this.bx, this.by, this.w, this.h, "w");
            // draw borders
            this.dr(this.bx, this.by, this.w, realbordersize, "b");
            this.dr(this.bx, this.by, realbordersize, this.h, "b");
            this.dr(this.bx, this.by + this.h - realbordersize, this.w, realbordersize, "b");
            this.dr(this.bx + this.w - realbordersize, this.by, realbordersize, this.h, "b");
        }
    }

    drawboxthinborderclicked() {
        this.dr(this.bx, this.by, this.w, this.h, "b");
    }

    drawboxnoborder() {
        this.dr(this.bx, this.by, this.w, this.h, "w");
    }

    drawboxnoborderclicked() {
        this.dr(this.bx, this.by, this.w, this.h, "w");
    }

    drawCorners(corner: string) {
        assertEq(5, this.w, "3D|");
        assertEq(5, this.h, "3C|");
        if (corner === "nw") {
            this.dr(this.bx, this.by + 0, 5, 1, "b");
            this.dr(this.bx, this.by + 1, 3, 1, "b");
            this.dr(this.bx, this.by + 2, 2, 1, "b");
            this.dr(this.bx, this.by + 3, 1, 1, "b");
            this.dr(this.bx, this.by + 4, 1, 1, "b");
        } else if (corner === "sw") {
            this.dr(this.bx, this.by + 0, 1, 1, "b");
            this.dr(this.bx, this.by + 1, 1, 1, "b");
            this.dr(this.bx, this.by + 2, 2, 1, "b");
            this.dr(this.bx, this.by + 3, 3, 1, "b");
            this.dr(this.bx, this.by + 4, 5, 1, "b");
        } else if (corner === "ne") {
            this.dr(this.bx + 0, this.by + 0, 5, 1, "b");
            this.dr(this.bx + 2, this.by + 1, 3, 1, "b");
            this.dr(this.bx + 3, this.by + 2, 2, 1, "b");
            this.dr(this.bx + 4, this.by + 3, 1, 1, "b");
            this.dr(this.bx + 4, this.by + 4, 1, 1, "b");
        } else if (corner === "se") {
            this.dr(this.bx + 4, this.by + 0, 1, 1, "b");
            this.dr(this.bx + 4, this.by + 1, 1, 1, "b");
            this.dr(this.bx + 3, this.by + 2, 2, 1, "b");
            this.dr(this.bx + 2, this.by + 3, 3, 1, "b");
            this.dr(this.bx + 0, this.by + 4, 5, 1, "b");
        }
    }
}
