
/* auto */ import { assertTrue } from '../../ui512/utils/utilsAssert.js';
/* auto */ import { RenderComplete, assertEq } from '../../ui512/utils/utilsUI512.js';
/* auto */ import { CanvasWrapper } from '../../ui512/utils/utilsDraw.js';

/* go straight to these, which are passed to the Canvas context object */
const cW = 'white'
const cB = 'black'

/**
 * draw borders, like buttons with shadows, window headers, and rounded rectangles
 * all loops completely unrolled, this code was generated by my Python script
 * border-img-to-js.py, which converts a png image to the code here.
 */
export class UI512ViewDrawBorders {
    didFallbackToSimpleRect = false;
    constructor(
        public canvas: CanvasWrapper,
        public bx: number,
        public by: number,
        public w: number,
        public h: number,
        public complete: RenderComplete
    ) {}

    /**
     * a wrapper around fillrect
     */
    public dr(x: number, y: number, w: number, h: number, color: string) {
        this.canvas.fillRect(x, y, w, h, this.bx, this.by, this.w, this.h, color, true);
    }

    /**
     * in original os, the borders would scale intelligently for very small boxes
     * we don't yet support this, we just fall back to a plain rectangle 
     */
    public fallbackToSimpleRect(highlight: boolean) {
        if (highlight) {
            this.drawboxthinborderclicked();
        } else {
            this.drawboxthinborder();
        }

        this.didFallbackToSimpleRect = true;
    }

    // BEGIN:GENERATED CODE --------------------------------------------------------------------------------------------------------
    // CODE GENERATED BY get-ui-borders.py, any changes here will be lost ----------------------------------------------------------
    /* osboxmodal.png */
public drawosboxmodal() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (6 + 6)) + 1
	if (w < 13) { return this.fallbackToSimpleRect(false); }
	if (h < 12) { return this.fallbackToSimpleRect(false); }
	if (h < 12) { return this.fallbackToSimpleRect(false); }
	
	/* drawing left side */
	stre_y=(h - (106 - 95))
	y = by
	this.dr(bx + 0, y, 1, 5, cB)
	y += 5
	this.dr(bx + 0, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 0, y, 1, 6, cB)
	y += 6
	
	y = by
	this.dr(bx + 1, y, 1, 1, cB)
	y += 1
	this.dr(bx + 1, y, 1, 4, cW)
	y += 4
	this.dr(bx + 1, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 1, y, 1, 5, cW)
	y += 5
	this.dr(bx + 1, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	this.dr(bx + 2, y, 1, 4, cW)
	y += 4
	this.dr(bx + 2, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 2, y, 1, 5, cW)
	y += 5
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	this.dr(bx + 3, y, 1, 2, cW)
	y += 2
	this.dr(bx + 3, y, 1, 2, cB)
	y += 2
	this.dr(bx + 3, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 3, y, 1, 3, cB)
	y += 3
	this.dr(bx + 3, y, 1, 2, cW)
	y += 2
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	this.dr(bx + 4, y, 1, 2, cW)
	y += 2
	this.dr(bx + 4, y, 1, 2, cB)
	y += 2
	this.dr(bx + 4, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 4, y, 1, 3, cB)
	y += 3
	this.dr(bx + 4, y, 1, 2, cW)
	y += 2
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr(bx + 5, y, 1, 1, cB)
	y += 1
	this.dr(bx + 5, y, 1, 2, cW)
	y += 2
	this.dr(bx + 5, y, 1, 2, cB)
	y += 2
	this.dr(bx + 5, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 5, y, 1, 1, cW)
	y += 1
	this.dr(bx + 5, y, 1, 2, cB)
	y += 2
	this.dr(bx + 5, y, 1, 2, cW)
	y += 2
	this.dr(bx + 5, y, 1, 1, cB)
	y += 1
	
	/* drawing middle */
	y = by
	this.dr(bx + 6, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 6, y, stre_x, 2, cW)
	y += 2
	this.dr(bx + 6, y, stre_x, 2, cB)
	y += 2
	this.dr(bx + 5, by + 5, stre_x, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 6, y, stre_x, 1, cW)
	y += 1
	this.dr(bx + 6, y, stre_x, 2, cB)
	y += 2
	this.dr(bx + 6, y, stre_x, 2, cW)
	y += 2
	this.dr(bx + 6, y, stre_x, 1, cB)
	y += 1
	
	/* drawing right side */
	stre_y=(h - (106 - 95))
	y = by
	this.dr((bx + w - 6) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 6) + 0, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 6) + 0, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 6) + 0, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr((bx + w - 6) + 0, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 6) + 0, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 6) + 0, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 6) + 0, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr((bx + w - 6) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 6) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 6) + 1, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 6) + 1, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr((bx + w - 6) + 1, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 6) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 6) + 1, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr((bx + w - 6) + 2, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 6) + 2, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 6) + 2, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 6) + 2, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr((bx + w - 6) + 2, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 6) + 2, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 6) + 2, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr((bx + w - 6) + 3, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 6) + 3, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 6) + 3, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr((bx + w - 6) + 3, y, 1, 5, cW)
	y += 5
	this.dr((bx + w - 6) + 3, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr((bx + w - 6) + 4, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 6) + 4, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 6) + 4, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr((bx + w - 6) + 4, y, 1, 5, cW)
	y += 5
	this.dr((bx + w - 6) + 4, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr((bx + w - 6) + 5, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 6) + 5, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr((bx + w - 6) + 5, y, 1, 6, cB)
	y += 6
	
	return true;
}

/* osboxshadow.png */
public drawosboxshadow() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (2 + 3)) + 1
	if (w < 6) { return this.fallbackToSimpleRect(false); }
	if (h < 5) { return this.fallbackToSimpleRect(false); }
	if (h < 5) { return this.fallbackToSimpleRect(false); }
	
	/* drawing left side */
	stre_y=(h - (44 - 40))
	y = by
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	this.dr(bx + 0, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr(bx + 0, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr(bx + 0, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 1, y, 1, 1, cB)
	y += 1
	this.dr(bx + 1, by + 1, 1, stre_y, cW)
	y=by + 1 + stre_y
	this.dr(bx + 1, y, 1, 1, cW)
	y += 1
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	
	/* drawing middle */
	y = by
	this.dr(bx + 2, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 1, by + 1, stre_x, stre_y, cW)
	y=by + 1 + stre_y
	this.dr(bx + 2, y, stre_x, 1, cW)
	y += 1
	this.dr(bx + 2, y, stre_x, 2, cB)
	y += 2
	
	/* drawing right side */
	stre_y=(h - (44 - 40))
	y = by
	this.dr((bx + w - 3) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 3) + 0, by + 1, 1, stre_y, cW)
	y=by + 1 + stre_y
	this.dr((bx + w - 3) + 0, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 3) + 0, y, 1, 2, cB)
	y += 2
	
	y = by
	this.dr((bx + w - 3) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 3) + 1, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr((bx + w - 3) + 1, y, 1, 3, cB)
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 3) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 3) + 2, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr((bx + w - 3) + 2, y, 1, 3, cB)
	y += 3
	
	return true;
}

/* osboxshadowclicked.png */
public drawosboxshadowclicked() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (2 + 3)) + 1
	if (w < 6) { return this.fallbackToSimpleRect(true); }
	if (h < 4) { return this.fallbackToSimpleRect(true); }
	if (h < 4) { return this.fallbackToSimpleRect(true); }
	
	/* drawing left side */
	stre_y=(h - (44 - 41))
	y = by
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	this.dr(bx + 0, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 0, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 1, y, 1, 1, cB)
	y += 1
	this.dr(bx + 1, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	
	/* drawing middle */
	y = by
	this.dr(bx + 2, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 1, by + 1, stre_x, stre_y, cB)
	y=by + 1 + stre_y
	this.dr(bx + 2, y, stre_x, 2, cB)
	y += 2
	
	/* drawing right side */
	stre_y=(h - (44 - 41))
	y = by
	this.dr((bx + w - 3) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 3) + 0, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr((bx + w - 3) + 0, y, 1, 2, cB)
	y += 2
	
	y = by
	this.dr((bx + w - 3) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 3) + 1, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr((bx + w - 3) + 1, y, 1, 2, cB)
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 3) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 3) + 2, by + 1, 1, stre_y, cB)
	y=by + 1 + stre_y
	this.dr((bx + w - 3) + 2, y, 1, 2, cB)
	y += 2
	
	return true;
}

/* osbtn.png */
public drawosbtn() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (5 + 5)) + 1
	if (w < 11) { return this.fallbackToSimpleRect(false); }
	if (h < 8) { return this.fallbackToSimpleRect(false); }
	if (h < 8) { return this.fallbackToSimpleRect(false); }
	
	/* drawing left side */
	stre_y=(h - (21 - 14))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 0, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 0, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	this.dr(bx + 1, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr(bx + 1, y, 1, 1, cW)
	y += 1
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr(bx + 1, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	this.dr(bx + 2, y, 1, 1, cW)
	y += 1
	this.dr(bx + 2, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr(bx + 2, y, 1, 2, cW)
	y += 2
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	this.dr(bx + 3, y, 1, 2, cW)
	y += 2
	this.dr(bx + 3, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr(bx + 3, y, 1, 3, cW)
	y += 3
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	this.dr(bx + 4, y, 1, 2, cW)
	y += 2
	this.dr(bx + 4, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr(bx + 4, y, 1, 3, cW)
	y += 3
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	
	/* drawing middle */
	y = by
	this.dr(bx + 5, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 5, y, stre_x, 2, cW)
	y += 2
	this.dr(bx + 4, by + 3, stre_x, stre_y, cW)
	y=by + 3 + stre_y
	this.dr(bx + 5, y, stre_x, 3, cW)
	y += 3
	this.dr(bx + 5, y, stre_x, 1, cB)
	y += 1
	
	/* drawing right side */
	stre_y=(h - (21 - 14))
	y = by
	this.dr((bx + w - 5) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 5) + 0, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 5) + 0, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 0, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 5) + 0, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr((bx + w - 5) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 5) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 5) + 1, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 1, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 5) + 1, y, 1, 1, cB)
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 5) + 2, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 5) + 2, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 5) + 2, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 2, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 5) + 2, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 5) + 3, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 5) + 3, by + 3, 1, stre_y, cW)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 3, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 5) + 3, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 5) + 4, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 4, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, cT) */
	y += 3
	
	return true;
}

/* osbtnclicked.png */
public drawosbtnclicked() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (5 + 5)) + 1
	if (w < 11) { return this.fallbackToSimpleRect(true); }
	if (h < 8) { return this.fallbackToSimpleRect(true); }
	if (h < 8) { return this.fallbackToSimpleRect(true); }
	
	/* drawing left side */
	stre_y=(h - (21 - 14))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 0, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 0, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	this.dr(bx + 1, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr(bx + 1, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 1, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 2, y, 1, 2, cB)
	y += 2
	this.dr(bx + 2, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr(bx + 2, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 3, y, 1, 3, cB)
	y += 3
	this.dr(bx + 3, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr(bx + 3, y, 1, 4, cB)
	y += 4
	
	y = by
	this.dr(bx + 4, y, 1, 3, cB)
	y += 3
	this.dr(bx + 4, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr(bx + 4, y, 1, 4, cB)
	y += 4
	
	/* drawing middle */
	y = by
	this.dr(bx + 5, y, stre_x, 3, cB)
	y += 3
	this.dr(bx + 4, by + 3, stre_x, stre_y, cB)
	y=by + 3 + stre_y
	this.dr(bx + 5, y, stre_x, 4, cB)
	y += 4
	
	/* drawing right side */
	stre_y=(h - (21 - 14))
	y = by
	this.dr((bx + w - 5) + 0, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 5) + 0, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 0, y, 1, 4, cB)
	y += 4
	
	y = by
	this.dr((bx + w - 5) + 1, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 5) + 1, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 1, y, 1, 4, cB)
	y += 4
	
	y = by
	/* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 5) + 2, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 5) + 2, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 2, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 5) + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 5) + 3, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 5) + 3, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 3, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 5) + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 5) + 4, by + 3, 1, stre_y, cB)
	y=by + 3 + stre_y
	this.dr((bx + w - 5) + 4, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 5) + 4, y, 1, 3, cT) */
	y += 3
	
	return true;
}

/* osdefaultbtn.png */
public drawosdefaultbtn() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (8 + 8)) + 1
	if (w < 17) { return this.fallbackToSimpleRect(false); }
	if (h < 16) { return this.fallbackToSimpleRect(false); }
	if (h < 16) { return this.fallbackToSimpleRect(false); }
	
	/* drawing left side */
	stre_y=(h - (29 - 14))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 5, cT) */
	y += 5
	this.dr(bx + 0, y, 1, 2, cB)
	y += 2
	this.dr(bx + 0, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 0, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 0, y, 1, 5, cT) */
	y += 5
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 1, y, 1, 4, cB)
	y += 4
	this.dr(bx + 1, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 1, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr(bx + 1, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 2, cT) */
	y += 2
	this.dr(bx + 2, y, 1, 5, cB)
	y += 5
	this.dr(bx + 2, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 2, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr(bx + 2, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr(bx + 3, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 3, y, 1, 5, cB)
	y += 5
	this.dr(bx + 3, y, 1, 1, cW)
	y += 1
	this.dr(bx + 3, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr(bx + 3, y, 1, 2, cW)
	y += 2
	this.dr(bx + 3, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr(bx + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 4, y, 1, 3, cB)
	y += 3
	this.dr(bx + 4, y, 1, 3, cW)
	y += 3
	this.dr(bx + 4, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	this.dr(bx + 4, y, 1, 3, cW)
	y += 3
	this.dr(bx + 4, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 5, y, 1, 4, cB)
	y += 4
	this.dr(bx + 5, y, 1, 1, cW)
	y += 1
	this.dr(bx + 5, y, 1, 2, cB)
	y += 2
	this.dr(bx + 5, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr(bx + 5, y, 1, 1, cW)
	y += 1
	this.dr(bx + 5, y, 1, 2, cB)
	y += 2
	this.dr(bx + 5, y, 1, 1, cW)
	y += 1
	this.dr(bx + 5, y, 1, 4, cB)
	y += 4
	
	y = by
	this.dr(bx + 6, y, 1, 3, cB)
	y += 3
	this.dr(bx + 6, y, 1, 2, cW)
	y += 2
	this.dr(bx + 6, y, 1, 1, cB)
	y += 1
	this.dr(bx + 6, y, 1, 1, cW)
	y += 1
	this.dr(bx + 6, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr(bx + 6, y, 1, 2, cW)
	y += 2
	this.dr(bx + 6, y, 1, 1, cB)
	y += 1
	this.dr(bx + 6, y, 1, 2, cW)
	y += 2
	this.dr(bx + 6, y, 1, 3, cB)
	y += 3
	
	y = by
	this.dr(bx + 7, y, 1, 3, cB)
	y += 3
	this.dr(bx + 7, y, 1, 1, cW)
	y += 1
	this.dr(bx + 7, y, 1, 1, cB)
	y += 1
	this.dr(bx + 7, y, 1, 2, cW)
	y += 2
	this.dr(bx + 7, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr(bx + 7, y, 1, 3, cW)
	y += 3
	this.dr(bx + 7, y, 1, 1, cB)
	y += 1
	this.dr(bx + 7, y, 1, 1, cW)
	y += 1
	this.dr(bx + 7, y, 1, 3, cB)
	y += 3
	
	/* drawing middle */
	y = by
	this.dr(bx + 8, y, stre_x, 3, cB)
	y += 3
	this.dr(bx + 8, y, stre_x, 1, cW)
	y += 1
	this.dr(bx + 8, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 8, y, stre_x, 2, cW)
	y += 2
	this.dr(bx + 7, by + 7, stre_x, stre_y, cW)
	y=by + 7 + stre_y
	this.dr(bx + 8, y, stre_x, 3, cW)
	y += 3
	this.dr(bx + 8, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 8, y, stre_x, 1, cW)
	y += 1
	this.dr(bx + 8, y, stre_x, 3, cB)
	y += 3
	
	/* drawing right side */
	stre_y=(h - (29 - 14))
	y = by
	this.dr((bx + w - 8) + 0, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 0, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 8) + 0, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 0, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 0, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 8) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 8) + 0, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 0, y, 1, 3, cB)
	y += 3
	
	y = by
	this.dr((bx + w - 8) + 1, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 8) + 1, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 1, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 8) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 1, y, 1, 3, cB)
	y += 3
	
	y = by
	this.dr((bx + w - 8) + 2, y, 1, 4, cB)
	y += 4
	this.dr((bx + w - 8) + 2, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 2, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 8) + 2, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 2, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 2, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 8) + 2, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 2, y, 1, 4, cB)
	y += 4
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 8) + 3, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 3, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 8) + 3, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 3, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 8) + 3, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 8) + 3, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 8) + 4, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 8) + 4, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 4, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 4, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 4, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, cT) */
	y += 2
	this.dr((bx + w - 8) + 5, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 8) + 5, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 5, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 8) + 6, y, 1, 4, cB)
	y += 4
	this.dr((bx + w - 8) + 6, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 6, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, cT) */
	y += 5
	this.dr((bx + w - 8) + 7, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 8) + 7, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 7, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, cT) */
	y += 5
	
	return true;
}

/* osdefaultbtnclicked.png */
public drawosdefaultbtnclicked() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (8 + 8)) + 1
	if (w < 17) { return this.fallbackToSimpleRect(true); }
	if (h < 16) { return this.fallbackToSimpleRect(true); }
	if (h < 16) { return this.fallbackToSimpleRect(true); }
	
	/* drawing left side */
	stre_y=(h - (29 - 14))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 5, cT) */
	y += 5
	this.dr(bx + 0, y, 1, 2, cB)
	y += 2
	this.dr(bx + 0, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 0, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 0, y, 1, 5, cT) */
	y += 5
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 1, y, 1, 4, cB)
	y += 4
	this.dr(bx + 1, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 1, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr(bx + 1, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 2, cT) */
	y += 2
	this.dr(bx + 2, y, 1, 5, cB)
	y += 5
	this.dr(bx + 2, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 2, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr(bx + 2, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr(bx + 3, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 3, y, 1, 5, cB)
	y += 5
	this.dr(bx + 3, y, 1, 1, cW)
	y += 1
	this.dr(bx + 3, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr(bx + 3, y, 1, 2, cW)
	y += 2
	this.dr(bx + 3, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr(bx + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 4, y, 1, 3, cB)
	y += 3
	this.dr(bx + 4, y, 1, 3, cW)
	y += 3
	this.dr(bx + 4, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	this.dr(bx + 4, y, 1, 3, cW)
	y += 3
	this.dr(bx + 4, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 5, y, 1, 4, cB)
	y += 4
	this.dr(bx + 5, y, 1, 1, cW)
	y += 1
	this.dr(bx + 5, y, 1, 2, cB)
	y += 2
	this.dr(bx + 5, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 5, y, 1, 3, cB)
	y += 3
	this.dr(bx + 5, y, 1, 1, cW)
	y += 1
	this.dr(bx + 5, y, 1, 4, cB)
	y += 4
	
	y = by
	this.dr(bx + 6, y, 1, 3, cB)
	y += 3
	this.dr(bx + 6, y, 1, 2, cW)
	y += 2
	this.dr(bx + 6, y, 1, 2, cB)
	y += 2
	this.dr(bx + 6, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 6, y, 1, 3, cB)
	y += 3
	this.dr(bx + 6, y, 1, 2, cW)
	y += 2
	this.dr(bx + 6, y, 1, 3, cB)
	y += 3
	
	y = by
	this.dr(bx + 7, y, 1, 3, cB)
	y += 3
	this.dr(bx + 7, y, 1, 1, cW)
	y += 1
	this.dr(bx + 7, y, 1, 3, cB)
	y += 3
	this.dr(bx + 7, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 7, y, 1, 4, cB)
	y += 4
	this.dr(bx + 7, y, 1, 1, cW)
	y += 1
	this.dr(bx + 7, y, 1, 3, cB)
	y += 3
	
	/* drawing middle */
	y = by
	this.dr(bx + 8, y, stre_x, 3, cB)
	y += 3
	this.dr(bx + 8, y, stre_x, 1, cW)
	y += 1
	this.dr(bx + 8, y, stre_x, 3, cB)
	y += 3
	this.dr(bx + 7, by + 7, stre_x, stre_y, cB)
	y=by + 7 + stre_y
	this.dr(bx + 8, y, stre_x, 4, cB)
	y += 4
	this.dr(bx + 8, y, stre_x, 1, cW)
	y += 1
	this.dr(bx + 8, y, stre_x, 3, cB)
	y += 3
	
	/* drawing right side */
	stre_y=(h - (29 - 14))
	y = by
	this.dr((bx + w - 8) + 0, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 0, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 0, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 0, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 0, y, 1, 4, cB)
	y += 4
	this.dr((bx + w - 8) + 0, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 0, y, 1, 3, cB)
	y += 3
	
	y = by
	this.dr((bx + w - 8) + 1, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 1, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 8) + 1, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 1, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 1, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 1, y, 1, 3, cB)
	y += 3
	
	y = by
	this.dr((bx + w - 8) + 2, y, 1, 4, cB)
	y += 4
	this.dr((bx + w - 8) + 2, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 2, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 8) + 2, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 2, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 2, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 2, y, 1, 4, cB)
	y += 4
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 8) + 3, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 8) + 3, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 8) + 3, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 3, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 8) + 3, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 8) + 3, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 8) + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 8) + 4, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 8) + 4, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 8) + 4, by + 7, 1, stre_y, cW)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 4, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 8) + 4, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr((bx + w - 8) + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, cT) */
	y += 2
	this.dr((bx + w - 8) + 5, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 8) + 5, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 5, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr((bx + w - 8) + 5, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 8) + 6, y, 1, 4, cB)
	y += 4
	this.dr((bx + w - 8) + 6, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 6, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr((bx + w - 8) + 6, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, cT) */
	y += 5
	this.dr((bx + w - 8) + 7, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 8) + 7, by + 7, 1, stre_y, cB)
	y=by + 7 + stre_y
	this.dr((bx + w - 8) + 7, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 8) + 7, y, 1, 5, cT) */
	y += 5
	
	return true;
}

/* vpcbtn.png */
public drawvpcbtn() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (9 + 7)) + 1
	if (w < 17) { return this.fallbackToSimpleRect(false); }
	if (h < 13) { return this.fallbackToSimpleRect(false); }
	if (h < 14) { return this.fallbackToSimpleRect(false); }
	
	/* drawing left side */
	stre_y=(h - (41 - 29))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 5, cT) */
	y += 5
	this.dr(bx + 0, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 0, y, 1, 6, cT) */
	y += 6
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	this.dr(bx + 1, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 1, y, 1, 1, cW)
	y += 1
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr(bx + 1, y, 1, 4, cT) */
	y += 4
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 2, cT) */
	y += 2
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	this.dr(bx + 2, y, 1, 2, cW)
	y += 2
	this.dr(bx + 2, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 2, y, 1, 3, cW)
	y += 3
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 2, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 3, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	this.dr(bx + 3, y, 1, 3, cW)
	y += 3
	this.dr(bx + 3, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 3, y, 1, 4, cW)
	y += 4
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 3, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	this.dr(bx + 4, y, 1, 3, cW)
	y += 3
	this.dr(bx + 4, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 4, y, 1, 4, cW)
	y += 4
	this.dr(bx + 4, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 5, y, 1, 1, cB)
	y += 1
	this.dr(bx + 5, y, 1, 4, cW)
	y += 4
	this.dr(bx + 5, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 5, y, 1, 5, cW)
	y += 5
	this.dr(bx + 5, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 5, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 6, y, 1, 1, cB)
	y += 1
	this.dr(bx + 6, y, 1, 4, cW)
	y += 4
	this.dr(bx + 6, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 6, y, 1, 5, cW)
	y += 5
	this.dr(bx + 6, y, 1, 2, cB)
	y += 2
	
	y = by
	this.dr(bx + 7, y, 1, 1, cB)
	y += 1
	this.dr(bx + 7, y, 1, 4, cW)
	y += 4
	this.dr(bx + 7, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 7, y, 1, 5, cW)
	y += 5
	this.dr(bx + 7, y, 1, 2, cB)
	y += 2
	
	y = by
	this.dr(bx + 8, y, 1, 1, cB)
	y += 1
	this.dr(bx + 8, y, 1, 4, cW)
	y += 4
	this.dr(bx + 8, by + 5, 1, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 8, y, 1, 5, cW)
	y += 5
	this.dr(bx + 8, y, 1, 2, cB)
	y += 2
	
	/* drawing middle */
	y = by
	this.dr(bx + 9, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 9, y, stre_x, 4, cW)
	y += 4
	this.dr(bx + 8, by + 5, stre_x, stre_y, cW)
	y=by + 5 + stre_y
	this.dr(bx + 9, y, stre_x, 5, cW)
	y += 5
	this.dr(bx + 9, y, stre_x, 2, cB)
	y += 2
	
	/* drawing right side */
	stre_y=(h - (41 - 28))
	y = by
	this.dr((bx + w - 7) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 0, y, 1, 5, cW)
	y += 5
	this.dr((bx + w - 7) + 0, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 0, y, 1, 5, cW)
	y += 5
	this.dr((bx + w - 7) + 0, y, 1, 2, cB)
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 1, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 7) + 1, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 1, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 7) + 1, y, 1, 3, cB)
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 2, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 2, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 7) + 2, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 2, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 7) + 2, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, cT) */
	y += 2
	this.dr((bx + w - 7) + 3, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 3, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 7) + 3, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 3, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 7) + 3, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 7) + 4, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 7) + 4, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 7) + 4, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 4, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 7) + 4, y, 1, 4, cB)
	y += 4
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, cT) */
	y += 4
	this.dr((bx + w - 7) + 5, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 7) + 5, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 5, y, 1, 4, cB)
	y += 4
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, cT) */
	y += 6
	this.dr((bx + w - 7) + 6, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 6, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 5, cT) */
	y += 5
	
	return true;
}

/* vpcbtnclicked.png */
public drawvpcbtnclicked() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (9 + 7)) + 1
	if (w < 17) { return this.fallbackToSimpleRect(true); }
	if (h < 13) { return this.fallbackToSimpleRect(true); }
	if (h < 13) { return this.fallbackToSimpleRect(true); }
	
	/* drawing left side */
	stre_y=(h - (41 - 29))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 5, cT) */
	y += 5
	this.dr(bx + 0, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 0, y, 1, 6, cT) */
	y += 6
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	this.dr(bx + 1, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 1, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 1, y, 1, 4, cT) */
	y += 4
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 2, cT) */
	y += 2
	this.dr(bx + 2, y, 1, 3, cB)
	y += 3
	this.dr(bx + 2, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 2, y, 1, 4, cB)
	y += 4
	/* (transparent) this.dr(bx + 2, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 3, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 3, y, 1, 4, cB)
	y += 4
	this.dr(bx + 3, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 3, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr(bx + 3, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 4, y, 1, 4, cB)
	y += 4
	this.dr(bx + 4, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 4, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 5, y, 1, 5, cB)
	y += 5
	this.dr(bx + 5, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 5, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr(bx + 5, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 6, y, 1, 5, cB)
	y += 5
	this.dr(bx + 6, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 6, y, 1, 7, cB)
	y += 7
	
	y = by
	this.dr(bx + 7, y, 1, 5, cB)
	y += 5
	this.dr(bx + 7, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 7, y, 1, 7, cB)
	y += 7
	
	y = by
	this.dr(bx + 8, y, 1, 5, cB)
	y += 5
	this.dr(bx + 8, by + 5, 1, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 8, y, 1, 7, cB)
	y += 7
	
	/* drawing middle */
	y = by
	this.dr(bx + 9, y, stre_x, 5, cB)
	y += 5
	this.dr(bx + 8, by + 5, stre_x, stre_y, cB)
	y=by + 5 + stre_y
	this.dr(bx + 9, y, stre_x, 7, cB)
	y += 7
	
	/* drawing right side */
	stre_y=(h - (41 - 29))
	y = by
	this.dr((bx + w - 7) + 0, y, 1, 6, cB)
	y += 6
	this.dr((bx + w - 7) + 0, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 0, y, 1, 6, cB)
	y += 6
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 1, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 7) + 1, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 1, y, 1, 6, cB)
	y += 6
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 2, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 7) + 2, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 2, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, cT) */
	y += 2
	this.dr((bx + w - 7) + 3, y, 1, 4, cB)
	y += 4
	this.dr((bx + w - 7) + 3, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 3, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 7) + 4, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 7) + 4, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 4, y, 1, 4, cB)
	y += 4
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, cT) */
	y += 4
	this.dr((bx + w - 7) + 5, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 7) + 5, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 5, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, cT) */
	y += 6
	this.dr((bx + w - 7) + 6, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 6, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 5, cT) */
	y += 5
	
	return true;
}

/* vpcroundrect.png */
public drawvpcroundrect() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (9 + 7)) + 1
	if (w < 17) { return this.fallbackToSimpleRect(false); }
	if (h < 14) { return this.fallbackToSimpleRect(false); }
	if (h < 14) { return this.fallbackToSimpleRect(false); }
	
	/* drawing left side */
	stre_y=(h - (40 - 27))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 6, cT) */
	y += 6
	this.dr(bx + 0, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 0, y, 1, 6, cT) */
	y += 6
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 4, cT) */
	y += 4
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	this.dr(bx + 1, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 1, y, 1, 1, cW)
	y += 1
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr(bx + 1, y, 1, 4, cT) */
	y += 4
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	this.dr(bx + 2, y, 1, 2, cW)
	y += 2
	this.dr(bx + 2, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 2, y, 1, 3, cW)
	y += 3
	this.dr(bx + 2, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 2, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 3, y, 1, 2, cT) */
	y += 2
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	this.dr(bx + 3, y, 1, 3, cW)
	y += 3
	this.dr(bx + 3, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 3, y, 1, 4, cW)
	y += 4
	this.dr(bx + 3, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 3, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	this.dr(bx + 4, y, 1, 4, cW)
	y += 4
	this.dr(bx + 4, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 4, y, 1, 5, cW)
	y += 5
	this.dr(bx + 4, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr(bx + 5, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 5, y, 1, 1, cB)
	y += 1
	this.dr(bx + 5, y, 1, 4, cW)
	y += 4
	this.dr(bx + 5, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 5, y, 1, 5, cW)
	y += 5
	this.dr(bx + 5, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 5, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 6, y, 1, 1, cB)
	y += 1
	this.dr(bx + 6, y, 1, 5, cW)
	y += 5
	this.dr(bx + 6, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 6, y, 1, 6, cW)
	y += 6
	this.dr(bx + 6, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr(bx + 7, y, 1, 1, cB)
	y += 1
	this.dr(bx + 7, y, 1, 5, cW)
	y += 5
	this.dr(bx + 7, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 7, y, 1, 6, cW)
	y += 6
	this.dr(bx + 7, y, 1, 1, cB)
	y += 1
	
	y = by
	this.dr(bx + 8, y, 1, 1, cB)
	y += 1
	this.dr(bx + 8, y, 1, 5, cW)
	y += 5
	this.dr(bx + 8, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 8, y, 1, 6, cW)
	y += 6
	this.dr(bx + 8, y, 1, 1, cB)
	y += 1
	
	/* drawing middle */
	y = by
	this.dr(bx + 9, y, stre_x, 1, cB)
	y += 1
	this.dr(bx + 9, y, stre_x, 5, cW)
	y += 5
	this.dr(bx + 8, by + 6, stre_x, stre_y, cW)
	y=by + 6 + stre_y
	this.dr(bx + 9, y, stre_x, 6, cW)
	y += 6
	this.dr(bx + 9, y, stre_x, 1, cB)
	y += 1
	
	/* drawing right side */
	stre_y=(h - (40 - 27))
	y = by
	this.dr((bx + w - 7) + 0, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 0, y, 1, 5, cW)
	y += 5
	this.dr((bx + w - 7) + 0, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 0, y, 1, 6, cW)
	y += 6
	this.dr((bx + w - 7) + 0, y, 1, 1, cB)
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 1, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 1, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 7) + 1, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 1, y, 1, 5, cW)
	y += 5
	this.dr((bx + w - 7) + 1, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 2, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 2, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 7) + 2, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 2, y, 1, 5, cW)
	y += 5
	this.dr((bx + w - 7) + 2, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, cT) */
	y += 2
	this.dr((bx + w - 7) + 3, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 3, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 7) + 3, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 3, y, 1, 4, cW)
	y += 4
	this.dr((bx + w - 7) + 3, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 7) + 4, y, 1, 1, cB)
	y += 1
	this.dr((bx + w - 7) + 4, y, 1, 2, cW)
	y += 2
	this.dr((bx + w - 7) + 4, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 4, y, 1, 3, cW)
	y += 3
	this.dr((bx + w - 7) + 4, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, cT) */
	y += 4
	this.dr((bx + w - 7) + 5, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 7) + 5, by + 6, 1, stre_y, cW)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 5, y, 1, 1, cW)
	y += 1
	this.dr((bx + w - 7) + 5, y, 1, 2, cB)
	y += 2
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, cT) */
	y += 4
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, cT) */
	y += 6
	this.dr((bx + w - 7) + 6, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 6, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, cT) */
	y += 6
	
	return true;
}

/* vpcroundrectclicked.png */
public drawvpcroundrectclicked() {
	const w=this.w;
	const h=this.h;
	const bx=this.bx;
	const by=this.by;
	let y=0;
	let stre_y=0;
	const stre_x=(w - (9 + 7)) + 1
	if (w < 17) { return this.fallbackToSimpleRect(true); }
	if (h < 14) { return this.fallbackToSimpleRect(true); }
	if (h < 14) { return this.fallbackToSimpleRect(true); }
	
	/* drawing left side */
	stre_y=(h - (40 - 27))
	y = by
	/* (transparent) this.dr(bx + 0, y, 1, 6, cT) */
	y += 6
	this.dr(bx + 0, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 0, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr(bx + 0, y, 1, 6, cT) */
	y += 6
	
	y = by
	/* (transparent) this.dr(bx + 1, y, 1, 4, cT) */
	y += 4
	this.dr(bx + 1, y, 1, 2, cB)
	y += 2
	this.dr(bx + 1, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 1, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr(bx + 1, y, 1, 4, cT) */
	y += 4
	
	y = by
	/* (transparent) this.dr(bx + 2, y, 1, 3, cT) */
	y += 3
	this.dr(bx + 2, y, 1, 3, cB)
	y += 3
	this.dr(bx + 2, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 2, y, 1, 4, cB)
	y += 4
	/* (transparent) this.dr(bx + 2, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr(bx + 3, y, 1, 2, cT) */
	y += 2
	this.dr(bx + 3, y, 1, 4, cB)
	y += 4
	this.dr(bx + 3, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 3, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr(bx + 3, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 4, y, 1, 5, cB)
	y += 5
	this.dr(bx + 4, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 4, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr(bx + 4, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr(bx + 5, y, 1, 1, cT) */
	y += 1
	this.dr(bx + 5, y, 1, 5, cB)
	y += 5
	this.dr(bx + 5, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 5, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr(bx + 5, y, 1, 1, cT) */
	y += 1
	
	y = by
	this.dr(bx + 6, y, 1, 6, cB)
	y += 6
	this.dr(bx + 6, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 6, y, 1, 7, cB)
	y += 7
	
	y = by
	this.dr(bx + 7, y, 1, 6, cB)
	y += 6
	this.dr(bx + 7, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 7, y, 1, 7, cB)
	y += 7
	
	y = by
	this.dr(bx + 8, y, 1, 6, cB)
	y += 6
	this.dr(bx + 8, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 8, y, 1, 7, cB)
	y += 7
	
	/* drawing middle */
	y = by
	this.dr(bx + 9, y, stre_x, 6, cB)
	y += 6
	this.dr(bx + 8, by + 6, stre_x, stre_y, cB)
	y=by + 6 + stre_y
	this.dr(bx + 9, y, stre_x, 7, cB)
	y += 7
	
	/* drawing right side */
	stre_y=(h - (40 - 27))
	y = by
	this.dr((bx + w - 7) + 0, y, 1, 6, cB)
	y += 6
	this.dr((bx + w - 7) + 0, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 0, y, 1, 7, cB)
	y += 7
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 1, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 7) + 1, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 1, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr((bx + w - 7) + 1, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	this.dr((bx + w - 7) + 2, y, 1, 5, cB)
	y += 5
	this.dr((bx + w - 7) + 2, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 2, y, 1, 6, cB)
	y += 6
	/* (transparent) this.dr((bx + w - 7) + 2, y, 1, 1, cT) */
	y += 1
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, cT) */
	y += 2
	this.dr((bx + w - 7) + 3, y, 1, 4, cB)
	y += 4
	this.dr((bx + w - 7) + 3, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 3, y, 1, 5, cB)
	y += 5
	/* (transparent) this.dr((bx + w - 7) + 3, y, 1, 2, cT) */
	y += 2
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, cT) */
	y += 3
	this.dr((bx + w - 7) + 4, y, 1, 3, cB)
	y += 3
	this.dr((bx + w - 7) + 4, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 4, y, 1, 4, cB)
	y += 4
	/* (transparent) this.dr((bx + w - 7) + 4, y, 1, 3, cT) */
	y += 3
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, cT) */
	y += 4
	this.dr((bx + w - 7) + 5, y, 1, 2, cB)
	y += 2
	this.dr((bx + w - 7) + 5, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 5, y, 1, 3, cB)
	y += 3
	/* (transparent) this.dr((bx + w - 7) + 5, y, 1, 4, cT) */
	y += 4
	
	y = by
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, cT) */
	y += 6
	this.dr((bx + w - 7) + 6, by + 6, 1, stre_y, cB)
	y=by + 6 + stre_y
	this.dr((bx + w - 7) + 6, y, 1, 1, cB)
	y += 1
	/* (transparent) this.dr((bx + w - 7) + 6, y, 1, 6, cT) */
	y += 6
	
	return true;
}

    // END:GENERATED CODE

    drawboxthinborder() {
        if (this.w > 0 && this.h > 0) {
            let realbordersize = 1;

            /* clear it */
            this.dr(this.bx, this.by, this.w, this.h, cW);

            /* draw borders */
            this.dr(this.bx, this.by, this.w, realbordersize, cB);
            this.dr(this.bx, this.by, realbordersize, this.h, cB);
            this.dr(this.bx, this.by + this.h - realbordersize, this.w, realbordersize, cB);
            this.dr(this.bx + this.w - realbordersize, this.by, realbordersize, this.h, cB);
        }
    }

    drawboxthinborderclicked() {
        this.dr(this.bx, this.by, this.w, this.h, cB);
    }

    drawboxnoborder() {
        this.dr(this.bx, this.by, this.w, this.h, cW);
    }

    drawboxnoborderclicked() {
        this.dr(this.bx, this.by, this.w, this.h, cW);
    }

    drawCorners(corner: string) {
        assertEq(5, this.w, '3D|');
        assertEq(5, this.h, '3C|');
        if (corner === 'nw') {
            this.dr(this.bx, this.by + 0, 5, 1, cB);
            this.dr(this.bx, this.by + 1, 3, 1, cB);
            this.dr(this.bx, this.by + 2, 2, 1, cB);
            this.dr(this.bx, this.by + 3, 1, 1, cB);
            this.dr(this.bx, this.by + 4, 1, 1, cB);
        } else if (corner === 'sw') {
            this.dr(this.bx, this.by + 0, 1, 1, cB);
            this.dr(this.bx, this.by + 1, 1, 1, cB);
            this.dr(this.bx, this.by + 2, 2, 1, cB);
            this.dr(this.bx, this.by + 3, 3, 1, cB);
            this.dr(this.bx, this.by + 4, 5, 1, cB);
        } else if (corner === 'ne') {
            this.dr(this.bx + 0, this.by + 0, 5, 1, cB);
            this.dr(this.bx + 2, this.by + 1, 3, 1, cB);
            this.dr(this.bx + 3, this.by + 2, 2, 1, cB);
            this.dr(this.bx + 4, this.by + 3, 1, 1, cB);
            this.dr(this.bx + 4, this.by + 4, 1, 1, cB);
        } else if (corner === 'se') {
            this.dr(this.bx + 4, this.by + 0, 1, 1, cB);
            this.dr(this.bx + 4, this.by + 1, 1, 1, cB);
            this.dr(this.bx + 3, this.by + 2, 2, 1, cB);
            this.dr(this.bx + 2, this.by + 3, 3, 1, cB);
            this.dr(this.bx + 0, this.by + 4, 5, 1, cB);
        }
    }
}
